### ISSUE TITLE
Cannot modify header information - error

### ISSUE THREAD

**Issue by ldstr** [TrinityNET/CentosAuth#1]
`Warning: Cannot modify header information - headers already sent by (output started at .../index.php:1) in .../index.php on line 53`

the code is shit lmaoo

**Comment by JakeLazaros** [comment]
This error would only be thrown if you're trying to modify the headers or, from past experiences, trying to reload the page after executing something using post data. What code is on that line?

**Comment by ldstr** [comment]
> This error would only be thrown if you're trying to modify the headers or, from past experiences, trying to reload the page after executing something using post data. What code is on that line?

`header("refresh:3; url=$yoursiteurl/Panel");`

**Comment by JakeLazaros** [comment]
Replace that line with:

echo "<meta http-equiv='Refresh' Content='3'; url='".$_SERVER."'>";
die();

**Comment by notsquirr3l** [comment]
> 
> 
> Replace that line with:
> 
> echo "<meta http-equiv='Refresh' Content='3'; url='".$_SERVER."'>";
> die();

Yikes man telling your users to implement a security vulnerability as a "fix" you're an amazing programmer, for anyone in future please read the link below & do not do this...

 https://www.php.net/manual/en/reserved.variables.server.php

**Comment by JakeLazaros** [comment]
> > Replace that line with:
> > echo "<meta http-equiv='Refresh' Content='3'; url='".$_SERVER."'>";
> > die();
> 
> Yikes man telling your users to implement a security vulnerability as a "fix" you're an amazing programmer, for anyone in future please read the link below & do not do this...
> 
> https://www.php.net/manual/en/reserved.variables.server.php

A security vulnerability? How can refreshing the page programatically be a security vulnerability? It can only be executed after the integrity of the user has been verified if you're going to be that petty and stupid about it. Care to explain how it's a security vuln, please?

**Comment by wnelson03** [comment]
Lol, it's so funny seeing Centos trying to code. What a joke. You should use `ob_start();` and `ob_end_flush();` to alleviate your issue

**Comment by JakeLazaros** [comment]
> Lol, it's so funny seeing Centos trying to code. What a joke. You should use `ob_start();` and `ob_end_flush();` to alleviate your issue

you look like a future sex offender.
